/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwwcharacterdatabase;

/**
 *
 * @author tiein
 */
public class addCharacterForm extends javax.swing.JFrame {

    /**
     * Creates new form addCharacterForm
     */
    public addCharacterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameField = new javax.swing.JTextField();
        healthField = new javax.swing.JTextField();
        auraField = new javax.swing.JTextField();
        reflexField = new javax.swing.JTextField();
        dadaField = new javax.swing.JTextField();
        herbField = new javax.swing.JTextField();
        potionsField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        healthLabel = new javax.swing.JLabel();
        auraLabel = new javax.swing.JLabel();
        reflexLabel = new javax.swing.JLabel();
        dadaLabel = new javax.swing.JLabel();
        herbLabel = new javax.swing.JLabel();
        potionsLabel = new javax.swing.JLabel();
        ciLabel = new javax.swing.JLabel();
        ciField = new javax.swing.JTextField();
        intField = new javax.swing.JTextField();
        intLabel = new javax.swing.JLabel();
        strengthLabel = new javax.swing.JLabel();
        strengthField = new javax.swing.JTextField();
        darkField = new javax.swing.JTextField();
        darkLabel = new javax.swing.JLabel();
        muLabel = new javax.swing.JLabel();
        muField = new javax.swing.JTextField();
        charismaField = new javax.swing.JTextField();
        charismaLabel = new javax.swing.JLabel();
        transLabel = new javax.swing.JLabel();
        transField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nameField.setText("jTextField1");

        healthField.setText("jTextField1");

        auraField.setText("jTextField1");

        reflexField.setText("jTextField1");

        dadaField.setText("jTextField1");

        herbField.setText("jTextField1");

        potionsField.setText("jTextField1");

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");

        healthLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        healthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        healthLabel.setText("Health");

        auraLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        auraLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        auraLabel.setText("Aura");

        reflexLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reflexLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reflexLabel.setText("Reflex");

        dadaLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        dadaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dadaLabel.setText("DADA");

        herbLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        herbLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        herbLabel.setText("Herb");

        potionsLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        potionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potionsLabel.setText("Potions");

        ciLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ciLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ciLabel.setText("CI");

        ciField.setText("jTextField1");

        intField.setText("jTextField1");

        intLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        intLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        intLabel.setText("Int");

        strengthLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        strengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        strengthLabel.setText("Strength");

        strengthField.setText("jTextField1");

        darkField.setText("jTextField1");

        darkLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        darkLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        darkLabel.setText("Dark");

        muLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        muLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        muLabel.setText("MU");

        muField.setText("jTextField1");

        charismaField.setText("jTextField1");

        charismaLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        charismaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        charismaLabel.setText("Charisma");

        transLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        transLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transLabel.setText("Trans");

        transField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(healthField)
                            .addComponent(healthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(auraField)
                            .addComponent(auraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reflexField)
                            .addComponent(reflexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dadaField)
                            .addComponent(dadaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(potionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(herbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(potionsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(herbLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(162, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ciLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ciField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(intField)
                            .addComponent(intLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(strengthField)
                            .addComponent(strengthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(darkField)
                            .addComponent(darkLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(muField)
                            .addComponent(muLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(charismaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(charismaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(transLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(healthLabel)
                    .addComponent(auraLabel)
                    .addComponent(reflexLabel)
                    .addComponent(dadaLabel)
                    .addComponent(herbLabel)
                    .addComponent(potionsLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(healthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reflexField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(herbField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciLabel)
                    .addComponent(intLabel)
                    .addComponent(strengthLabel)
                    .addComponent(darkLabel)
                    .addComponent(muLabel)
                    .addComponent(transLabel)
                    .addComponent(charismaLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(muField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(charismaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCharacterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCharacterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCharacterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCharacterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCharacterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField auraField;
    private javax.swing.JLabel auraLabel;
    private javax.swing.JTextField charismaField;
    private javax.swing.JLabel charismaLabel;
    private javax.swing.JTextField ciField;
    private javax.swing.JLabel ciLabel;
    private javax.swing.JTextField dadaField;
    private javax.swing.JLabel dadaLabel;
    private javax.swing.JTextField darkField;
    private javax.swing.JLabel darkLabel;
    private javax.swing.JTextField healthField;
    private javax.swing.JLabel healthLabel;
    private javax.swing.JTextField herbField;
    private javax.swing.JLabel herbLabel;
    private javax.swing.JTextField intField;
    private javax.swing.JLabel intLabel;
    private javax.swing.JTextField muField;
    private javax.swing.JLabel muLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField potionsField;
    private javax.swing.JLabel potionsLabel;
    private javax.swing.JTextField reflexField;
    private javax.swing.JLabel reflexLabel;
    private javax.swing.JTextField strengthField;
    private javax.swing.JLabel strengthLabel;
    private javax.swing.JTextField transField;
    private javax.swing.JLabel transLabel;
    // End of variables declaration//GEN-END:variables
}
